### ISSUE TITLE
PA Review: User Auth

### ISSUE THREAD

**Issue by Tsanta96** [Tsanta96/soundwave#2]
- [x] Users can sign up, sign in, log out
- [x] Users can use a demo login to try the site
- [x] Users can't use certain features without logging in

**Comment by wongshington** [comment]
- [x] errors should clear from one form to another. 
   - I shouldn't see the invalid credentials form when I close the login form and switch to sign up
- [x] include a way to switch from form to form
- [x] styling: the errors are kind of barely hangin on at the end of the form
- [x] able to close the modal when clicking outside of the form(not just on the X)

**Comment by wongshington** [comment]
looks good to me. biggest suggestion at this point would be to change the text on the forms from "Log In"/ "Sign Up" to something more personable/welcoming
